# Generated by Django 4.0.4 on 2022-05-07 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='The author first name', max_length=100)),
                ('last_name', models.CharField(help_text='The author last name', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Born on')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died on')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'date_of_death'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The book title.', max_length=200)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('summary', models.TextField(help_text='A brief summary of the book.', max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A book genre (e.g. Science-Fiction).', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1708f621-f971-4825-a090-9b671cdbb938'), help_text='Unique identifier for the book copy.', primary_key=True, serialize=False)),
                ('imprint', models.CharField(help_text='The legal notice of the book.', max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('loan', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('l', 'On loan'), ('r', 'Reserved'), ('a', 'Available')], default='m', help_text='The book availability status.', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book')),
            ],
            options={
                'ordering': ['-due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='The book genre.', to='catalog.genre'),
        ),
    ]
