# Generated by Django 4.0.4 on 2022-05-07 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AR', 'Arabic'), ('ZH', 'Chinese (Mandarin)'), ('EN', 'English'), ('FR', 'French'), ('DE', 'German'), ('EL', 'Greek'), ('IT', 'Italian'), ('JA', 'Japanese'), ('KO', 'Korean'), ('LA', 'Latin'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ES', 'Spanish'), ('SW', 'Swahili')], default='EN', help_text='The language of the book.', max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for the book copy.', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(help_text='The language of the book.', to='catalog.language'),
        ),
    ]
