# Generated by Django 4.0.4 on 2022-05-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_book_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, choices=[('AR', 'Arabic'), ('ZH', 'Chinese (Mandarin)'), ('EN', 'English'), ('FR', 'French'), ('DE', 'German'), ('EL', 'Greek'), ('IT', 'Italian'), ('JA', 'Japanese'), ('KO', 'Korean'), ('LA', 'Latin'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ES', 'Spanish'), ('SW', 'Swahili')], default='EN', help_text='The language of the book.', max_length=2),
        ),
    ]
