# Generated by Django 4.0.4 on 2022-05-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_book_languages_book_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='loan',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('r', 'Reserved'), ('a', 'Available')], default='m', help_text='The book availability status.', max_length=1),
        ),
    ]
