# Generated by Django 4.0.4 on 2022-05-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='languages',
            new_name='language',
        ),
    ]
