# Generated by Django 4.0.4 on 2022-05-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_languages_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='loan',
            new_name='status',
        ),
    ]
