# Generated by Django 4.0.4 on 2022-05-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name', 'date_of_birth', 'date_of_death'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
